--Exam Answers 
CREATE OR ALTER PROCEDURE SP_Exam_Answers 
	@Exam_Id INT, @Student_Email VARCHAR(50),
	@A1 VARCHAR(20),@A2 VARCHAR(20),@A3 VARCHAR(20),@A4 VARCHAR(20),@A5 VARCHAR(20),
	@A6 VARCHAR(20),@A7 VARCHAR(20),@A8 VARCHAR(20),@A9 VARCHAR(20),@A10 VARCHAR(20)
AS
	BEGIN
		DECLARE @SID INT
		DECLARE @COUNTER INT=0
		DECLARE @QID INT
		DECLARE @Question_IDS TABLE(QID INT) 

		SELECT @SID=S.St_Id FROM Student S WHERE S.St_Email=@Student_Email

		IF NOT EXISTS(SELECT TE.E_Id FROM Take_Exam TE WHERE TE.E_Id=@Exam_Id AND TE.St_Id=@SID)
		BEGIN
			INSERT INTO @Question_IDS 
			SELECT  EQ.Q_Id 
			FROM Exam_Question EQ
			WHERE EQ.E_Id= @Exam_Id

			DECLARE CQIDS CURSOR FOR SELECT VQID.QID FROM @Question_IDS VQID
		
			OPEN  CQIDS
				FETCH NEXT FROM CQIDS INTO @QID
				WHILE @@FETCH_STATUS=0
				BEGIN 
					SET @COUNTER =@COUNTER+1
					INSERT INTO Take_Exam
					VALUES(@Exam_Id,@SID,@QID,
					CASE 
						WHEN @COUNTER=1 THEN @A1
						WHEN @COUNTER=2 THEN @A2
						WHEN @COUNTER=3 THEN @A3
						WHEN @COUNTER=4 THEN @A4
						WHEN @COUNTER=5 THEN @A5
						WHEN @COUNTER=6 THEN @A6
						WHEN @COUNTER=7 THEN @A7
						WHEN @COUNTER=8 THEN @A8
						WHEN @COUNTER=9 THEN @A9
						ELSE @A10
					END
					)

					FETCH NEXT FROM CQIDS INTO @QID
				END
			CLOSE CQIDS
			DEALLOCATE CQIDS
		END
		ELSE
			SELECT 'Your answer submitted'
	END


EXECUTE SP_Exam_Answers 5 ,'sara.mohamed456@example.com','A','B','C','A','A','A','A','B','B','B'
SELECT * FROM TAKE_EXAM